name: Run tests

on:
  push:
    branches: [ master, dev ]
  pull_request:
    branches: [ master, dev ]

jobs:
  run-tests:

    runs-on: ${{ matrix.os }}

    strategy:
      matrix:
        os: [ ubuntu-latest ]
        php: [ 8.0, 8.1 ]
        dependency-version: [ prefer-lowest, prefer-stable ]

    name: ${{ matrix.os }} - PHP ${{ matrix.php }} - ${{ matrix.dependency-version }}

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Setup PHP
      uses: shivammathur/setup-php@v2
      with:
        php-version: ${{ matrix.php }}
        coverage: none

    - name: Validate composer.json and composer.lock
      run: composer validate

    - name: Install dependencies
      if: steps.composer-cache.outputs.cache-hit != 'true'
      run: composer update --${{ matrix.dependency-version }} --prefer-dist --no-progress --no-interaction --no-suggest

    - name: Run test suite
      run: composer run-script test
